# SimpleStaffChat2 by Refrac
#--------------------------------------
# Placeholders: (PlaceholderAPI is supported)
# %player% - Get the player name
# %displayname% - Get the player display name
# %server% - Get the player server
# %message% - Get the message
# %arrow% - Get an arrow for a message
# %arrow_2% - Get alt arrow for a message
# %star% - Get a star for a message
# %circle% - Get a circle for a message
# %empty% - Disable any message with this placeholder
#--------------------------------------
# Used to send messages to staffchat without the
# need to type in /staffchat <message> or /staffchattoggle
# this uses the same format as /staffchat <message>
staffchat-symbol: "@"

format:
  # Minecraft format
  minecraft-format: "%prefix% &e(%server%) &6&l%player%&7: &f%message%"

# This is for staff joins only
# permissions: simplestaffchat.join, simplestaffchat.switch, simplestaffchat.quit
join:
  enabled: true
  join-format: "&8[&a+&8] &9%player% &fjoined &e%server%&f."
  switch-format: "&8[&b+&8] &9%player% &fswitched server &7(&e%from% &f%arrow% &e%server%&7)&f."
  quit-format: "&8[&c-&8] &9%player% &fleft &e%server%&f."

messages:
  prefix: "&8[&4&lStaffChat&8]"
  no-permission: "&cYou don't have permission to execute this command."
  reload: "&7Config files reloaded. Changes should be live in-game."
  toggle-on: "%prefix% &eStaffChat toggled &aon&7."
  toggle-off: "%prefix% &eStaffChat toggled &coff&7."

# These changes will require a restart of your BungeeCord/Proxy server
commands:
  staffchat:
    enabled: true
    # Command without /
    command: "staffchat"
    alias: "sc"
  toggle:
    enabled: true
    # Command without /
    command: "staffchattoggle"
    alias: "sctoggle"
  reload:
    enabled: true
    # Command without /
    command: "staffchatreload"
    alias: "screload"