# SimpleStaffChat2 by RefracDevelopment
#--------------------------------------
# Placeholders: (PlaceholderAPI is supported)
# %player% - Get the player name
# %displayname% - Get the player display name
# %message% - Get the message
# %arrow% - Get an arrow for a message
# %arrow_2% - Get alt arrow for a message
# %star% - Get a star for a message
# %circle% - Get a circle for a message
# %empty% - Disable any message with this placeholder
#--------------------------------------
# Used to send messages to staffchat without the
# need to type in /staffchat <message> or /staffchattoggle
# this uses the same format as /staffchat <message>
staffchat-symbol: "#"
# Used to send messages to adminchat without the
# need to type in /adminchat <message> or /adminchattoggle
# this uses the same format as /adminchat <message>
adminchat-symbol: "@"
# Used to send messages to devchat without the
# need to type in /devchat <message> or /devchattoggle
# this uses the same format as /devchat <message>
devchat-symbol: "%"

format:
  # AdminChat format
  adminchat-format: "&8[&c&lAdminChat&8] &c&l%player%&7: &f%message%"
  # DevChat format
  devchat-format: "&8[&d&lDevChat&8] &b&l%player%&7: &f%message%"
  # Minecraft format
  minecraft-format: "%prefix% &6&l%player%&7: &f%message%"
  # Format for messages sent by the console
  # PlaceholderAPI is not supported here
  console-staffchat-format: "%prefix% &6&lConsole&7: &f%message%"
  # Format for messages sent by the console
  # PlaceholderAPI is not supported here
  console-adminchat-format: "&8[&c&lAdminChat&8] &c&lConsole&7: &f%message%"
  # Format for messages sent by the console
  # PlaceholderAPI is not supported here
  console-devchat-format: "&8[&d&lDevChat&8] &e&lConsole&7: &f%message%"

# This is for staff joins only
# permission: simplestaffchat.join or simplestaffchat.quit
join:
  enabled: false
  join-format: "&8[&a+&8] &9%player% &fjoined&f."
  quit-format: "&8[&c-&8] &9%player% &fleft&f."

messages:
  prefix: "&8[&4&lStaffChat&8]"
  no-permission: "&cYou don't have permission to execute this command."
  reload: "&7Config files reloaded. Changes should be live in-game."
  toggle-on: "%prefix% &7StaffChat toggled &aon&7."
  toggle-off: "%prefix% &7StaffChat toggled &coff&7."
  adminchat-toggle-on: "&8[&c&lAdminChat&8] &7AdminChat toggled &aon&7."
  adminchat-toggle-off: "&8[&c&lAdminChat&8] &7AdminChat toggled &coff&7."
  devchat-toggle-on: "&8[&d&lDevChat&8] &7DevChat toggled &aon&7."
  devchat-toggle-off: "&8[&d&lDevChat&8] &7DevChat toggled &coff&7."
  # If this is set to "custom" you can change the /sc output message to anything
  # If this is set to "toggle" you can use /sc to toggle into staffchat easier
  staffchat-output: "default"
  # staffchat-output must be set to "custom" in order for this to work
  staffchat-message:
    - ""
    - "&c&lSimpleStaffChat2 %arrow2% Help"
    - ""
    - "&c/staffchat <message> - Send staffchat messages."
    - "&c/adminchat <message> - Send adminchat messages."
    - "&c/devchat <message> - Send devchat messages."
    - "&c/staffchattoggle - Send staffchat messages without needing to type a command."
    - "&c/adminchattoggle - Send adminchat messages without needing to type a command."
    - "&c/devchattoggle - Send devchat messages without needing to type a command."
    - "&c/staffchatreload - Reload the config file."
    - ""

# You will need to reload the config for these changes /staffchatreload
commands:
  staffchat:
    enabled: true
    # Command without /
    alias:
      - "sc"
  adminchat:
    enabled: true
    # Command without /
    alias:
      - "ac"
  devchat:
    enabled: true
    # Command without /
    alias:
      - "dc"
  toggle:
    enabled: true
    # Command without /
    alias:
      - "sctoggle"
      - "sct"
  adminchat-toggle:
    enabled: true
    # Command without /
    alias:
      - "actoggle"
      - "act"
  devchat-toggle:
    enabled: true
    # Command without /
    alias:
      - "dctoggle"
      - "dct"
  reload:
    enabled: true
    # Command without /
    alias:
      - "screload"