name: SimpleStaffChat2
version: '@version@'
main: me.refracdevelopment.simplestaffchat.spigot.SimpleStaffChat
author:  RefracDevelopment
api-version: "1.13"
softdepend:
  - PlaceholderAPI
description: A Simple StaffChat Plugin
website: https://discord.refracdev.ml/

permissions:
  simplestaffchat.*:
    default: op
    description: Gives all permissions
    children:
      simplestaffchat.command.help: true
      simplestaffchat.command.staffchat: true
      simplestaffchat.command.staffchat.toggle: true
      simplestaffchat.command.reload: true
      simplestaffchat.staffchat.see: true
      simplestaffchat.staffchat.symbol: true
      simplestaffchat.join: true
      simplestaffchat.quit: true
  simplestaffchat.command.help:
    default: op
    description: Allows you to see the help page
  simplestaffchat.command.staffchat:
    default: op
    description: Allows you to use the staffchat command
  simplestaffchat.command.staffchat.toggle:
    default: op
    description: Allows you to toggle staffchat
  simplestaffchat.command.reload:
    default: op
    description: Allows you to reload the config file
  simplestaffchat.staffchat.see:
    default: op
    description: Allows you to see the staffchat messages
  simplestaffchat.staffchat.symbol:
    default: op
    description: Allows you to use the staffchat symbol
  simplestaffchat.join:
    default: op
    description: Sends a join message when a staff member joins.
  simplestaffchat.quit:
    default: op
    description: Sends a join message when a staff member leaves the server.