name: 'SimpleStaffChat'
version: '${project.version}'
main: me.refrac.simplestaffchat.spigot.SimpleStaffChat
softdepend:
  - PlaceholderAPI
author: 'Refrac'
description: 'A Lightweight StaffChat Plugin'
website: 'https://discord.gg/jVnmm7QnQU'

commands:
  staffchat:
    description: Send messages to your staff privately
    aliases:
      - sc
  staffchattoggle:
    description: Toggle sending messages to your staff privately
    aliases:
      - sctoggle
  staffchatreload:
    description: Reload the configuration file
    aliases:
      - screload