name: 'SimpleStaffChat2'
version: '${project.version}'
main: me.refrac.simplestaffchat.spigot.SimpleStaffChat
softdepend:
  - PlaceholderAPI
author: 'Refrac'
description: 'A Lightweight StaffChat Plugin'
website: 'https://discord.gg/jVnmm7QnQU'

commands:
  staffchat:
    description: 'Send messages to your staff privately'
  staffchattoggle:
    description: 'Toggle sending messages to your staff privately'
  staffchatreload:
    description: 'Reload the plugin'