name: 'SimpleStaffChat2'
version: '${project.version}'
main: me.refracdevelopment.simplestaffchat.spigot.SimpleStaffChat
softdepend:
  - PlaceholderAPI
authors:
  - 'RefracDevelopment'
  - 'Refrac'
description: 'A Simple StaffChat Plugin'
website: 'https://discord.gg/EFeSKPg739'